const MENU_PROPERTIES = {
    HEIGHT: '50px',
    MAX_WIDTH: '1300px',
    WIDTH_NUMBER: 1300,
}

const MENU_SCALE_PROPERTIES = {
    WIDTH: '250px',
    HEIGHT: '500px',
    BORDER_RADIUS: '16px',
    TOP: '60px',
}

const HOMEPAGE_PROPERTIES = {
    MAX_WIDTH: '1300px',

}


const PRODUCT_REVIEW_PAGE_PROPERTIES = {
    MAX_WIDTH: '1300px',

}


const ITEM_PRODUCT_PROPERTIES = {
    WIDTH: '250px',
    
}

export {
    MENU_PROPERTIES,
    MENU_SCALE_PROPERTIES,
    HOMEPAGE_PROPERTIES,
    ITEM_PRODUCT_PROPERTIES,
    PRODUCT_REVIEW_PAGE_PROPERTIES,
    
}